### ISSUE TITLE
Mouse wrapping occasionally freezes the program with an error

### ISSUE THREAD

**Issue by vanjac** [vanjac/three#15]
When the mouse crosses to the other side of the window while hidden, a `RuntimeError` is occasionally thrown, especially when the mouse is moving quickly. This is due to the use of multiple threads when calling `pyautogui` methods. The full error is:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jacob/git/three/threelib/appInstance/gl.py", line 249, in moveToTop
    + 3 * self.mouseLockMargin)
  File "/usr/lib/python3.5/site-packages/pyautogui/__init__.py", line 648, in moveRel
    _mouseMoveDrag('move', None, None, xOffset, yOffset, duration, tween)
  File "/usr/lib/python3.5/site-packages/pyautogui/__init__.py", line 786, in _mouseMoveDrag
    startx, starty = position()
  File "/usr/lib/python3.5/site-packages/pyautogui/__init__.py", line 199, in position
    posx, posy = platformModule._position()
  File "/usr/lib/python3.5/site-packages/pyautogui/_pyautogui_x11.py", line 24, in _position
    coord = _display.screen().root.query_pointer()._data
  File "/usr/lib/python3.5/site-packages/Xlib/xobject/drawable.py", line 562, in query_pointer
    window = self.id)
  File "/usr/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1481, in __init__
    self.reply()
  File "/usr/lib/python3.5/site-packages/Xlib/protocol/rq.py", line 1493, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 720, in parse_request_response
    req = self.get_waiting_replyrequest()
  File "/usr/lib/python3.5/site-packages/Xlib/protocol/display.py", line 847, in get_waiting_replyrequest
    raise RuntimeError("Request reply to unknown request.  Can't happen!")
RuntimeError: Request reply to unknown request.  Can't happen!
```

**Comment by vanjac** [comment]
Fixed with 45ea815ba5e3325250fac3f5994df22ea78589f1
